### ISSUE TITLE
Map Tool not propery integrated

### ISSUE THREAD

**Issue by signedav** [opengisch/qgis-linking-relation-editor#16]
On having the linking relation editor widget on a child layer with geometry, when I want to add a feature (with geometry) I receive this error:

```
Traceback (most recent call last):
  File "/home/dave/.local/share/QGIS/QGIS3/profiles/default/python/plugins/linking_relation_editor/gui/linking_relation_editor_widget.py", line 433, in addFeatureGeometry
    self.mMapToolDigitize.setLayer(layer)
AttributeError: 'LinkingRelationEditorWidget' object has no attribute 'mMapToolDigitize'

```

**Comment by signedav** [comment]
@domi4484 After a quick look in the code it seems that this member is not implemented. Would it be a big thing to make that? Maybe it's not a big deal not to have it (but then we need to disable the button and care that model baker does not take this type on geometry references).

**Comment by domi4484** [comment]
Yes thre are just some methods to "pythonize" from the c++ implementation...
