### ISSUE TITLE
Upgradet minimum QGIS version in version 1.0.0

### ISSUE THREAD

**Issue by signedav** [opengisch/qgis-linking-relation-editor#22]
Hi @domi4484 

For your info. I upgraded the minimum QGIS Version to 3.22 for Version 1.0.0 in the Plugin Repository here:https://plugins.qgis.org/plugins/linking_relation_editor/

Because otherwise the 1.0.0 version got installed on 3.16 what leaded to an error with the abstract class of the widget.

You can close this issue if acknowledged.

**Comment by domi4484** [comment]
@signedav Yes it makes sense. Theoretically it should work starting from version 3.18, but then some bugs where fixed in QgsAbstractRelationEditor so I think going for 3.22 is a good choice (and versions 18 and 20 are probably not much used).
